SHOW_COMMANDS = [
    "show access-list",
    "show access-session",
    "show adjacency",
    "show alert counters",
    "show aliases",
    "show ap summary",
    "show archive",
    "show authentication sessions",
    "show bfd neighbors details",
    "show bfd neighbors details",
    "show boot",
    "show capability feature routing",
    "show cdp neighbors",
    "show cdp neighbors detail",
    "show clock",
    "show controller t1",
    "show crypto ipsec sa detail",
    "show crypto pki certificates",
    "show crypto session detail",
    "show dhcp lease",
    "show dmvpn",
    "show dot1x all",
    "show environment power all",
    "show environment temperature",
    "show etherchannel summary",
    "show hosts summary",
    "show interface link",
    "show interface transceiver",
    "show interfaces",
    "show interfaces description",
    "show interfaces status",
    "show interfaces switchport",
    "show inventory",
    "show ip access-lists",
    "show ip arp",
    "show ip bgp",
    "show ip bgp neighbors",
    "show ip bgp neighbors advertised-routes",
    "show ip bgp summary",
    "show ip bgp vpnv4 all neighbors",
    "show ip cef",
    "show ip cef detail",
    "show ip device tracking all",
    "show ip eigrp interfaces detail",
    "show ip eigrp neighbors",
    "show ip eigrp topology",
    "show ip eigrp topology",
    "show ip flow toptalkers",
    "show ip http server status",
    "show ip http server status",
    "show ip interface",
    "show ip interface brief",
    "show ip mroute",
    "show ip nat translations",
    "show ip ospf database",
    "show ip ospf database network",
    "show ip ospf database router",
    "show ip ospf interface brief",
    "show ip ospf neighbor",
    "show ip prefix-list",
    "show ip route",
    "show ip route summary",
    "show ip source binding",
    "show ip vrf interfaces",
    "show ipv6 access-lists",
    "show ipv6 interface brief",
    "show ipv6 neighbors",
    "show ipv6 route",
    "show isdn status",
    "show isis neighbors",
    "show license",
    "show lldp neighbors",
    "show lldp neighbors detail",
    "show logging",
    "show mac-address-table",
    "show module",
    "show module online diag",
    "show module status",
    "show module submodule",
    "show mpls interfaces",
    "show nve peers",
    "show nve vni",
    "show object-group",
    "show platform diag",
    "show port-security interface interface",
    "show port-security interface interface",
    "show power available",
    "show power status",
    "show power supplies",
    "show processes cpu",
    "show processes memory sorted",
    "show redundancy",
    "show route-map",
    "show running-config partition access-list",
    "show running-config partition route-map",
    "show snmp community",
    "show snmp group",
    "show snmp user",
    "show spanning-tree",
    "show standby",
    "show standby brief",
    "show switch detail",
    "show switch detail stack ports",
    "show tacacs",
    "show version",
    "show vlan",
    "show vrf",
    "show vrrp all",
    "show vrrp brief",
    "show vtp status"
]